version: '3.8'
services:
  deno:
    image: denoland/deno:alpine-1.14.1
    volumes: [.:/app:ro]
    working_dir: /app
    command: deno test --allow-net --filter "$TEST_FILTER"
    environment:
      - TEST_FILTER

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
